import help from "./help.png";
import project from "./projects.png";
import gitRepo from "./git-repo.png";
import terminal from "./terminal.png";
import addFolder from "./add-folder.png";
import fileStates from "./file-states.png";
import addItem from "./add-folder-item.png";
import matchOrders from "./match-orders.png";
import endDayButton from "./end-day-button.png";
import orderArriving from "./order-arriving.png";
import gitWorkingDir from "./git-working-dir.png";
import gitWorkScreen from "./git-work-screen.png";
import gitStagingArea from "./git-staging-area.png";
import terminalCommands from "./terminal_commands.png";
import gitFetchTerminal from "./fetch-content-terminal.png";
import gitFetchBranches from "./fetch-content-branches.png";
import terminalCommandsClone from "./terminal_commands_clone.png";

export const imgHelp = help;
export const imgProject = project;
export const imgGitRepo = gitRepo;
export const imgTerminal = terminal;
export const imgAddFolders = addFolder;
export const imgFileStates = fileStates;
export const imgAddFolderItem = addItem;
export const imgMatchOrders = matchOrders;
export const imgEndDayButton = endDayButton;
export const imgOrderArriving = orderArriving;
export const imgGitWorkingDir = gitWorkingDir;
export const imgGitWorkScreen = gitWorkScreen;
export const imgGitStagingArea = gitStagingArea;
export const imgGitFetchTerminal = gitFetchTerminal;
export const imgGitFetchBranches = gitFetchBranches;
export const imgTerminalCommands = terminalCommands;
export const imgTerminalCommandsClone = terminalCommandsClone;
