import help from "assets/tutorials/help.png";
import terminal from "assets/tutorials/terminal.png";
import orderArriving from "assets/tutorials/order-arriving.png";
import fileStates from "assets/tutorials/file-states.png";
import addFolder from "assets/tutorials/add-folder.png";
import addItem from "assets/tutorials/add-folder-item.png";
import matchOrders from "assets/tutorials/match-orders.png";
import gitRepo from "assets/tutorials/git-repo.png";
import gitStagingArea from "assets/tutorials/git-staging-area.png";
import gitWorkingDir from "assets/tutorials/git-working-dir.png";
import gitWorkScreen from "assets/tutorials/git-work-screen.png";
import gitFetchTerminal from "assets/tutorials/fetch-content-terminal.png";
import gitFetchBranches from "assets/tutorials/fetch-content-branches.png";

export const imgHelp = help;
export const imgTerminal = terminal;
export const imgFileStates = fileStates;
export const imgOrderArriving = orderArriving;
export const imgMatchOrders = matchOrders;
export const imgAddFolders = addFolder;
export const imgAddFolderItem = addItem;
export const imgGitRepo = gitRepo;
export const imgGitStagingArea = gitStagingArea;
export const imgGitWorkingDir = gitWorkingDir;
export const imgGitWorkScreen = gitWorkScreen;
export const imgGitFetchTerminal = gitFetchTerminal;
export const imgGitFetchBranches = gitFetchBranches;
