import logo from "assets/logo.png";
import chef from "assets/chef.png";
import fire from "assets/fire.png";
import paddy from "assets/paddy.png";
import clock from "assets/clock.png";
import salad from "assets/salad.png";
import fries from "assets/fries.png";
import onions from "assets/onions.png";
import bunTop from "assets/bun_top.png";
import command from "assets/command.png";
import discount from "assets/discount.png";
import bunBottom from "assets/bun_bottom.png";
import brickWall from "assets/brick_wall.png";
import cheeseFries from "assets/cheese_fries.png";
import costReduction from "assets/cost_reduction.png";
import revenueMultiplier from "assets/revenue_multiplier.png";

export const imgLogo = logo;
export const imgChef = chef;
export const imgFire = fire;
export const imgPaddy = paddy;
export const imgSalad = salad;
export const imgFries = fries;
export const imgClock = clock;
export const imgOnions = onions;
export const imgBunTop = bunTop;
export const imgCommand = command;
export const imgDiscount = discount;
export const imgBunBottom = bunBottom;
export const imgBrickWall = brickWall;
export const imgCheeseFries = cheeseFries;
export const imgCostReduction = costReduction;
export const imgRevenueMultiplier = revenueMultiplier;
